classdef UitoggletoolConverter < appmigration.internal.ComponentConverter
    % UITOGGLETOOLCONVERTER Converter for uitoggletool
    
    % Copyright 2017-2020 The MathWorks, Inc.
    
    methods
        function [componentCreationFunction, issues] = getComponentCreationFunction(~, ~)
            % GETCOMPONENTCREATIONFUNCTION - Override superclass method.
            
            componentCreationFunction = @uitoggletool;
            issues = [];
        end
        
        function conversionFuncs = getCallbackConversionFunctions(~, ~)
            % GETCALLBACKCONVERSIONFUNCTIONS - Override superclass method.
            
            import appmigration.internal.CommonCallbackConversionUtil;
            
            conversionFuncs = {...
                {'ButtonDownFcn'  , @CommonCallbackConversionUtil.convertUnsupportedCallback},...
                {'ClickedCallback', @CommonCallbackConversionUtil.convertOneToOneCallback},...
                {'CreateFcn'      , @CommonCallbackConversionUtil.convertCreateFcn},...
                {'DeleteFcn'      , @CommonCallbackConversionUtil.convertDeleteFcn},...
                {'OffCallback'    , @CommonCallbackConversionUtil.convertOneToOneCallback},...
                {'OnCallback'     , @CommonCallbackConversionUtil.convertOneToOneCallback},...
                };
        end
        
        function conversionFuncs = getPropertyConversionFunctions(~)
            % GETPROPERTYCONVERSIONFUNCTIONS - Override superclass method.

            import appmigration.internal.CommonPropertyConversionUtil;
            
            conversionFuncs = {...
                {'BusyAction'         , @CommonPropertyConversionUtil.convertOneToOneProperty},...
                {'CData'              , @CommonPropertyConversionUtil.convertCData},...
                {'Enable'             , @CommonPropertyConversionUtil.convertEnable},...
                {'HandleVisibility'   , @CommonPropertyConversionUtil.convertOneToOneProperty},...
                {'Interruptible'      , @CommonPropertyConversionUtil.convertOneToOneProperty},...
                {'Separator'          , @CommonPropertyConversionUtil.convertOneToOneProperty},...
                {'State'              , @CommonPropertyConversionUtil.convertOneToOneProperty},...
                {'Tag'                , @CommonPropertyConversionUtil.convertOneToOneProperty},...
                {'Tooltip'            , @CommonPropertyConversionUtil.convertOneToOneProperty},...
                {'UserData'           , @CommonPropertyConversionUtil.convertUserData},...
                {'Visible'            , @CommonPropertyConversionUtil.convertOneToOneProperty},...
                };
        end
    end
end